[tool.poetry]
name = "tap-linkedin"
version = "0.0.1"
description = "`tap-linkedin` is a Singer tap for linkedin, built with the Meltano SDK for Singer Taps."
authors = ["Meltano"]
keywords = [
    "ELT",
    "linkedin",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
requests = "^2.25.1"
singer-sdk = "^0.26.0"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.4"
flake8 = "^3.9.2"
black = "^23.1.0"
pydocstyle = "^6.1.1"
mypy = "^0.910"
types-requests = "^2.26.1"
isort = "^5.10.1"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_linkedin"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-linkedin-ads = 'tap_linkedin.tap:TapLinkedIn.cli'
